name: Build LaTeX CV with XeLaTeX

on:[push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Inkscape (for SVG to PDF conversion)
      run: sudo apt-get update && sudo apt-get install -y inkscape


    - name: Compile with XeLaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        latexmk_use_xelatex: true

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: CV-PDF
        path: main.pdf
