name: Build LaTeX document

on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for pushing later

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Configure Git for this repo
        run: |
          git config --global user.name "MilanKacar"
          git config --global user.email "milankacar@live.com"

      - name: Commit and push compiled PDF to this repo
        run: |
          cp main.pdf Milan_Kacar_CV.pdf
          git add Milan_Kacar_CV.pdf
          git commit -m "Add latest compiled CV PDF [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
            repository: MilanKacar/CV
            ref: 'master'
            token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          cp main.pdf Milan_Kacar_CV.pdf
          git add Milan_Kacar_CV.pdf
          git commit -m "Add latest compiled CV PDF [skip ci]" || echo "No changes to commit"
          git push
