name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Milan_Kacar_CV.pdf

      - name: Commit updated data
        run: |
          git config --global user.name "MilanKacar"
          git config --global user.email "milankacar@live.com"

          # Show git status for debugging
          git status

          # Check for any changes in the repository
          if [ -n "$(git status --porcelain)" ]; then
            git add Milan_Kacar_CV.pdf
            git commit -m "Update visit count"
            git push
          else
            echo "No changes to commit"
          fi
