name: Build LaTeX document

on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for pushing later

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Configure Git for this repo
        run: |
          git config --global user.name "MilanKacar"
          git config --global user.email "milankacar@live.com"

      - name: Commit and push compiled PDF to this repo
        run: |
          cp main.pdf milan_kacar_cv.pdf
          git add milan_kacar_cv.pdf
          git commit -m "Add latest compiled CV PDF [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- REPLACED CLONE STEP ---
      - name: Clone target repo (CV) using token
        # This is a more robust way to clone in a GitHub Action
        uses: actions/checkout@v4
        with:
          repository: MilanKacar/CV
          path: target-repo
          token: ${{ secrets.update-cv-token }}
          # The token is passed as a parameter here, which is cleaner
          # and less error-prone than embedding it in the URL.

      - name: Commit and push PDF to CV repo
        run: |
          cd target-repo
          
          # This command removes the conflicting HTTP headers set by the runner
          # It fixes authentication issues when pushing to a different repo
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          
          git config --global user.name "MilanKacar"
          git config --global user.email "milankacar@live.com"
          cp ../main.pdf assets/img/Milan_Kacar_CV.pdf
          git add assets/img/Milan_Kacar_CV.pdf
          git commit -m "Auto-update CV PDF from cv-pdf" || echo "No changes to commit"
          # Push to the origin, which is now authenticated by the checkout action
          git push origin master
